# Problem set 4 {#sec-ps4}

:::{.callout-tip}
## Note
Note that Q1 and Q4 are new to complement the coverage on numerical solutions of PDEs.`
:::

## Q1. Finite difference formulae {.unnumbered}

The finite-difference formulae used in our numerical ODE and PDE schemes can be derived using Taylor series approximations. Consider a function $U$ that can be expanded as a Taylor series. 

a. Show that 
$$
\begin{gathered}
U(x + h) = U(x) + hU'(x) + \frac{h^2}{2}U''(x) + \frac{h^3}{6}U'''(x) + \cdots, \\
U(x - h) = U(x) - hU'(x) + \frac{h^2}{2}U''(x) - \frac{h^3}{6}U'''(x) + \cdots.
\end{gathered}
$$

b. By subtracting the two equations above, derive the centred difference formula used for the first-derivatives in our algorithms:
$$
U'(x) = \frac{U(x + h) - U(x - h)}{2h} + O(h^2).
$$
This is what's known as the centred difference formula for the derivative.

c. By adding the two Taylor series equations above, derive the centred difference formula used for the second-derivatives in our algorithms: 
$$
U''(x) = \frac{U(x + h) - 2U(x) + U(x - h)}{h^2} + O(h^2).
$$

d. The centered difference formula for $U'(x)$ will not immediately work if it is applied to find the derivative at the first mesh point in a discretisation, e.g. $x = x_0$. Show that the forward difference formula at $x = x_0$ can be derived as 
$$
U'(x_0) = \frac{-3U(x_0) + 4U(x_1) - U(x_2)}{2h} + O(h^2).
$$

Hint: consider as well the Taylor series for $U(x + 2h)$ and then combine the expansions for $U(x + h)$ and $U(x + 2h)$ to derive the result.

## Q2. The wine cellar problem I {.unnumbered} 

From @sec-wine-cellar, we have the heat system:
$$
\begin{gathered}
\frac{\partial T}{\partial t} = \kappa \frac{\partial^2 T}{\partial x^2}, \\
T(x = 0, t) = A \cos(\omega t), \\
|T(x, t)| \text{ is bounded as $x \to \infty$}.
\end{gathered}
$$
for $x \geq 0$. The initial condition can be ignored.

The solution was sought in the form of $T(x, t) = G(t) H(x)$ using a separation of variables procedure leading to $\frac{G'}{G} = \kappa \frac{H''}{H} = \lambda$. Go through an argument that the cases of $lambda = 0$ and $\lambda$ real lead to incompatible solutions. Review the calculation that $\lambda = i\omega$ leads to the desired solution given in the lecture notes. 

## Q3. The wine cellar problem II {.unnumbered} 

Review the code written on the Noteable repository that implements the explicit Euler scheme for the wine cellar problem.

* Verify how well the numerical solution matches the exact analytical solution by overlaying the numerical solution with the analytical solution.
* Investigate the solutions under different choices of parameters and time-stepping tolerances until you are confident you know how the numerical algorithm works.

## Q4. von Neumann analysis {.unnumbered}

Use von Neumann analysis to determine the stability of the explicit Euler scheme for the 4th order diffusion equation: 
$$
u_t = -u_{xxxx}.
$$
You may use the fact that the centred difference approximation of the fourth derivative is: 
$$
u_{xxxx}(x_j) \approx \frac{u_{j-2} - 4u_{j-1} + 6u_j - 4u_{j+1} + u_{j+2}}{\Delta x^4}.
$$

The stability criterion should be 
$$
\Delta t \leq \frac{\Delta x^4}{8}.
$$


<!-- 
## Q5. Budyko's model {.unnumbered} 

Previously we derived the energy for outgoing radiation as:
$$
E_{\text{out}}(T) = \sigma \gamma T^4, 
$$ 
which is estimated via the Stefan-Boltzmann law. Budyko's approximation replaces this law with a linear relationship.  

a. Assume that 
$$
T = T_0 + \bar{T},
$$ 
where $T_0 = 273.15 \, \mathrm{K}$, which corresponds to $0^\circ \, \mathrm{C}$. We can consider $\bar{T}$ as measured in Celcius (since conversion between Kelvins and Celcius is directly proportional). Substitute the above into $E_{\text{out}}$ and linearise, thus assuming $\bar{T}$ is near zero. Place the energy in the form
$$
E_{\text{out}} \sim A + B\bar{T}.
$$ 
Using the standard value of $\sigma = 5.67 \times 10^{-8}$ W/m<sup>2</sup> K<sup>4</sup> and $\gamma = 1$, calculate the values of $A$ and $B$. 

b. Rather than use the formal values derived above, the standard Budyko model uses values of $A = 203.3 \mathrm{W}/\mathrm{m}^2$ and $B = 2.09 \, \mathrm{W}/(\mathrm{m}^2 {}^\circ \mathrm{C})$ that are found from best fit with observational data. 
	
	Using Jupyter and a short script for numerical root finding, investigate the equilibrium solutions of 
$$
Q(1 - a(T_0 + \bar{T})) = A + B \bar{T}.
$$ 
where $Q = 342 \, \mathrm{W}/\mathrm{m}^2$ and $a(T)$ is given from (@eq-albedokaper). Where are the equilibrium solutions, $\bar{T^*}$, and how do they compare with those obtained previously using the Stefan-Boltzmann relation?
-->

## Q5. Variable Sun output {.unnumbered}

Satellite data indicates that $Q$, varies roughly between 341.37 W/m<sup>2</sup> and 341.75 W/m<sup>2</sup>, with a period of about 11 years.

a. Use the simple EBM (@eq-energy-ss), given by 
$$
Q(1 - a) = \sigma \gamma T^4,
$$ 
with a constant albedo, $a = 0.3$ and greenhouse gas factor $\gamma = 0.6$ to estimate the resultant variation (max and min) in the Earth's mean surface temperature $T$.

b. Similar to (a) but this time, use the Budyko balance equation, 
$$
Q(1 - a) = A + BT
$$ 
with $A = 203.3 \, \mathrm{W} \mathrm{m}^{-2}$ and $B = 2.09 \, \mathrm{W}/(\mathrm{m}^{2} \, {}^\circ \mathrm{C})$ to estimate the resultant variation in the surface temperature. Use $a = 0.3$. 

c. The actual variation in surface temperature is in fact less than what you computed above. Why might this be? 

## Q6. Phase line analysis {.unnumbered}

Consider the energy balance equation 
$$
C \frac{\mathrm{d}T}{\mathrm{d}t} = Q(1 - a(T)) - \sigma \gamma T^4 \equiv G(T).
$$ {#eq-ps4-main}
with $a$ given by (@eq-albedokaper). Because the differential equation is autonomous, we can apply phase-line analysis in order to qualitatively understand the evolution. Below is a plot of the function $G$:

```{python}
import numpy as np
import matplotlib.pyplot as plt

Q = 342; sigma = 5.67e-8; gam = 0.6;
a = lambda T: 0.5 - 0.2*np.tanh(0.1*(T-265));
T = np.linspace(220, 310, 100);
G = Q*(1-a(T)) - sigma*gam*T**4
fig, ax = plt.subplots()
ax.plot(T, G)
ax.grid(); ax.minorticks_on();
# Customize the major grid
ax.grid(which='major', linestyle='-', linewidth='0.5', color='red')
# Customize the minor grid
ax.grid(which='minor', linestyle=':', linewidth='0.5', color='black')
plt.xlabel('T (in Kelvins)'); plt.ylabel('G(T)');
```

a. Sketch the solution $T(t)$ of this equation for $t > 0$ if $T(0) = 230, 240, 260, 270$ and $300$. 

b. Sketch the solution $T(t)$ of this equation for $t > 0$ if $T(0) = 285$. Then sketch the solution of this equation with the same initial data in the same coordinate system if $C$ is twice as large. Explain your answer. 

c. If $\gamma$ is decreased due to the increased greenhouse effect, the entire curve is shifted upwards. Sketch the solution if $T(0) = 280$. Sketch the solution with the same initial data if $\gamma$ is decreased. Explain your answer.

<!--
## Q4. Evolution {.unnumbered}

Consider again (@eq-ps4-main). Let $T^*$ be a steady-state solution and set $T = T^* + u(t)$ where $u(t)$ is a small perturbation from the steady state.

a. Show that the perturbation satisfies 
$$
C \dot{u} = -D u + O(u^2).
$$
and hence solve for the general solution of the leading-order perturbation (ignoring quadratic terms). What are the conditions on $T^*$ so that the steady state is linearly stable? 

b. Assuming $T^*$ is linearly stable, find the typical response time to a perturbation. For instance, what is the time it takes for the perturbation to reach the value $u(t) = 0$ if $u(0) = 1$? How does this response time change with $C$? What is the physical interpretation of this regarding the climate?  

## Q5. Integral of energy over the planet {.unnumbered}

Ignoring the effects of albedo, the total radiation absorbed over the surface of the planet (per unit time) is given by 
$$
\iint_{\text{planet}} Qs(y=\sin\varphi) \, \mathrm{d}S.
$$
This is what is known as a surface integral (@sec-appendix-surfaceintegral). In the case of the spherical coordinate system, this is calculated by 
$$
\int_{\theta=0}^{2\pi} \int_{\varphi = -\pi/2}^{\pi/2} Qs(y = \sin\varphi) R_E^2 \cos\varphi \, \mathrm{d}\varphi \mathrm{d}\theta.
$$
Use the properties of $s(y)$ in (@eq-EBM-s) to conclude that the total radiation absorbed is $4\pi R_E^2 Q$.

## Q6. Mean temperature in the latitude-dependent EBM {.unnumbered}

Consider now the latitude-dependent EBM 
$$
C \frac{\partial T}{\partial t} = Qs(y)[1 - a(y)] - (A + BT) + k(\bar{T} - T).
$$ 
Recall the albedo is given by $a = a_i$ for $y > y_s$ and $a = a_w$ for $y < y_s$. 

a. By integrating the above equation over $y \in [0, 1]$, show that the mean temperature is given by 
$$
C \frac{\mathrm{d}\bar{T}}{\mathrm{d}t} = Q(1 - \bar{a}) - (A + B\bar{T}),
$$ {#eq-meanT-evo-ps}
where 
$$
\bar{a} = \int_0^1 s(y) a(y) \, \mathrm{d}y = \alpha_w \int_0^{y_s} s(y) \, \mathrm{d}y + a_i \int_{y_s}^1 s(y) \, \mathrm{d}y.
$$
b. In the case that $s$ is given by (@eq-EBM-s), show that 
$$
\bar{a} = a_i + (a_w - a_i) y_s[1 - 0.241(y_s^2 - 1)].
$$ {#eq-ps4-abar}
What is $\bar{a}$ in the two situations of a completely ice-covered world and an ice-free world?


b. Using Python, plot a graph of the steady-state temperature, $T^*$, which satisfies
$$
\bar{T}^* = \frac{Q(1 - \bar{a}) - A}{B},
$$ {#eq-ps4-Tbar}
as a function of the ice line location, $y_s \in [0, 1]$. 

c. In the numerical code designed in lectures `ma30287/notebooks/lecture17-latitudeebm_newton.ipynb` we used numerical quadratic to determine $\bar{T}$. Experiment with a modest number of mesh points and verify how well the integration scheme compares with the exact solution shown above.
-->
