# Problem class 2: dimensional analysis {#sec-pclass-dim}


:::{.callout-tip}
## Abstraction

It may seem strange to study examples from elementary physics in a course that is supposed to be about Planet Earth. But simple examples are the best ways to learn these important techniques. The full climate equations are often very involved. These toy models still nevertheless capture the spirit of what you must do when attacking any scientific problem.
:::

In this problem class, we will practice some concepts about non-dimensionalising in preparation for the Problem Set 1 in @sec-PS1. We will cover these two strategies in choosing scalings.

:::{.callout-important}
## Scaling principle 1

Select the characteristic scales so that as many of the possible non-dimensional numbers, $\Pi_i$, $i = 1, 2, 3, \ldots$ are normalised.
:::

:::{.callout-important}
## Scaling principle 2

Select characteristic scales so that no terms in the model diverge in the physical limit of interest.
:::

Here are the problems we shall do in the problem class. 



## Projectile motion

A projectile of mass $M$ (in $\mathrm{kg}$) is launched vertically with initial velocity $V_0$ (in $\mathrm{m} \; \mathrm{s}^{-1}$) from a position $Y_0$ (in $\mathrm{m}$) above the surface. Thus the mass's position, $Y(t)$ is governed by Newton's second law (applied to the mass and the mass of the Earth) and the set of equations
$$
\begin{gathered}
M Y_{tt} = - \frac{g R_E^2 M}{(R_E + Y)^2}, \\
Y(0) = Y_0,
\end{gathered}
$$
where $g = 9.81 \mathrm{m} \; \mathrm{s}^{-2}$ and $R_E = 6.4 \times 10^6 \mathrm{m}$ is the radius of the Earth.

1. Non-dimensionalise the equation using arbitary length and time scales. 

2. Identify the non-dimensional constants, $\Pi_i$.

3. Choose a length scale of $L = Y_0$ and time scale of $T = (L/g)^{1/2}$. Discuss the resultant equation and the interpretation of choosing these scales. 
4. Does your above choice allow you to easily study the limit of $R_E \to \infty$? If the limit can be taken, reduce the governing system to a simpler equation. 

5. Does your choice in Q3 allow you to easily study the limit of $Y_0 \to 0$? If not, choose an alternative choice of length and time scales and in that case, reduce the set of equations. 

## Terminal velocity 

A ball of radius $R$ (in $\mathrm{m}$) and uniform density $\rho$ (in $\mathrm{kg} \, \mathrm{m}^{-3}$) falls in a viscous fluid. The fluid has density $\rho_f$ (in $\mathrm{kg} \, \mathrm{m}^{-3}$) and viscosity (a measure of friction or resistance) $\mu$ (in $\mathrm{kg} \, \mathrm{m}^{-1} \, \mathrm{s}^{-1}$)). 
The equation that governs the velocity is 
$$
\begin{gathered}
\frac{4}{3} \pi R^3 \rho \frac{\mathrm{d}V}{\mathrm{d}t} = \frac{4}{3} \pi R^3 (\rho - \rho_f) g - 6\pi \mu R V, \\
V(0) = V_0.
\end{gathered}
$$

1. Choose appropriate velocity and time scales to non-dimensionalise the equation so as to leave only a single non-dimensional number on the drag term (the last term on the right hand-side). 

2. Define the non-dimensional parameter expressing a ratio between drag force and gravity force by the Stokes number (St) and confirm that it is
$$
St = \frac{9\mu V_0}{2(\rho - \rho_f) g R^3}.
$$

3. Comment on the two limits of $St \to 0$ and $St \to \infty$. Can the problem be reduced in these two limits? If so, reduce and solve.

## Navier-Stokes Equations

Consider the Navier-Stokes equations (which is a set of equations that dictates fluid flow):
$$\frac{\partial \boldsymbol{u}}{\partial t}+\left( \boldsymbol{u} \cdot \nabla \right)\boldsymbol{u}=-\frac{1}{\rho}\nabla p+\nu \nabla^2 \boldsymbol{u}.$$
The parameters and variables are as follows:

* $\boldsymbol{x}=(x, y, z)^{\mathrm{T}}$ is the direction field (each with dimension $\mathrm{m}$)
* $\boldsymbol{u}=(u, v, w)^{\mathrm{T}}$ is the velocity field where $u$ is the movement along the $x$-direction, $v$ is the movement along the $y$-direction and $w$ is the movement along the $z$-direction (each with dimension $\mathrm{m} \, \mathrm{s}^{-1}$)
* $t$ is time (dimension $\mathrm{s}$)
* $\rho$ is the fluid density (dimension $\mathrm{kg} \, \mathrm{m}^{-3}$)
* $\nu$ is the dynamic viscosity, which represents the resistance to flow due to gravity (with dimension $\mathrm{m}^2 \, \mathrm{s}^{-1}$)
* $p$ is the internal pressure of the fluid (dimension $\mathrm{kg} \, \mathrm{m}^{-1} \, \mathrm{s}^{-2}$)
* $\nabla=\left( \frac{\partial}{\partial x}, \frac{\partial}{\partial y}, \frac{\partial}{\partial z} \right)^{\mathrm{T}}$ is the gradient operator (each with the with effective dimension $\mathrm{m}^{-1}$).
* $\frac{\partial}{\partial t}$ is the partial time derivative (with effective dimension $\mathrm{s}^{-1}$)
* $\nabla^2=\frac{\partial^2}{\partial x^2}+\frac{\partial^2}{\partial y^2}+\frac{\partial^2}{\partial z^2}$ is the Laplacaian operator (with effective dimension $\mathrm{m}^{-2}$).

1.  Non-dimensionalise the equation using arbitrary length, time, speed and pressure scales.

:::{.callout-note collapse="true"}

# Non-dimensionalisation
Consider the following arbitrary non-dimensionalisation:
$$\boldsymbol{x}=[x]\boldsymbol{x}', \quad \boldsymbol{u}=[u]\boldsymbol{u}', \quad t=[t]t', \quad p=[p]p'$$
where $[x']=[u']=[t']=[p']=1$ are the new non-dimensional quantities whereas $[x]=\mathrm{m}, [u]=\mathrm{m} \, \mathrm{s}^{-1}, [t]=\mathrm{s}$ and $[p]=\mathrm{kg} \, \mathrm{m}^{-3}$.

Replacing these into the Navier-Stokes equation gives
$$\frac{[u]}{[t]}\frac{\partial \boldsymbol{u'}}{\partial t'}+\frac{[u]^2}{[x]}\left( \boldsymbol{u}' \cdot \nabla' \right)\boldsymbol{u}'=-\frac{[p]}{[x]\rho}\nabla' p'+\frac{\nu [u]}{[x]^2} \nabla'^2 \boldsymbol{u}'$$
where $\nabla'$ is the gradient operator in the new coordinate space $(x', y', z')$, i.e. $\nabla'=\left( \frac{\partial}{\partial x'}, \frac{\partial}{\partial y'}, \frac{\partial}{\partial z'} \right)^{\mathrm{T}}$.  Similarly, the operator $\nabla'^2$ is the Laplacian in the new coordinate space, i.e. $\nabla'^2=\frac{\partial^2}{\partial x'^2}+\frac{\partial^2}{\partial y'^2}+\frac{\partial^2}{\partial z'^2}$.
:::

2.  Rearrange the equation so that the coefficient of the time derivative is equal to 1.

:::{.callout-note collapse="true"}
# Time Derivative Coefficient

The dashes will be dropped henceforth for ease of notation.  Rearranging to make the coefficient of the time derivative 1 gives
$$\frac{\partial \boldsymbol{u}}{\partial t}+\frac{[u][t]}{[x]}\left( \boldsymbol{u} \cdot \nabla \right)\boldsymbol{u}=-\frac{[p][t]}{[u] [x] \rho}\nabla p+\frac{\nu [t]}{[x]^2} \nabla^2 \boldsymbol{u}.$$
:::

3.  Choose an appropriate time scale so that the coefficient of the pressure derivative is 1, then rearrange until only one term in the equation has a coefficient.

:::{.callout-note collapse="true"}

# Pressure Derivative
In order to eliminate the coefficient of the pressure derivative, suppose that the choice of the non-dimensionalisation is
$$\frac{[p][t]}{\rho [x] [u]}=1.$$
This means that the term $[p]$ can be written as
$$P=\frac{\rho [u] [x]}{[t]}.$$

> Checking the dimensions:
$$[P]=[\rho] [u] [x] [t]^{-1}=\left(\mathrm{kg} \, \mathrm{m}^{-3} \right) \, \left( \mathrm{m} \, \mathrm{s}^{-1} \right) \, \left( \mathrm{m} \right) \, \left(\mathrm{s}\right)^{-1}=\mathrm{kg} \, \mathrm{m}^{-1} \, \mathrm{s}^{-2}$$
which is indeed the dimension for pressure.

Suppose that the term $\frac{[u] [t]}{[x]}$ should also be equal to 1, then this would mean that the time non-dimensionalisation can be done by having $[t]=\frac{[x]}{[u]}$.

> Checking the dimensions:
$$[t]=[x][u]^{-1}=\left( \mathrm{m} \right) \, \left( \mathrm{m} \, \mathrm{s}^{-1} \right)^{-1}=\mathrm{s}$$
which is indeed the dimension for time.

Therefore, with these choices of $[t]$ and $[p]$, the Navier-Stokes equation becomes
$$\frac{\partial \boldsymbol{u}}{\partial t}+\left( \boldsymbol{u} \cdot \nabla \right)\boldsymbol{u}=-\nabla p+\frac{\nu}{[u] [x]} \nabla^2 \boldsymbol{u}.$$
:::

4.  Let $\mathrm{Re}=\frac{[x] [u]}{\nu}$, known as the **Reynolds number**.  Show that $\mathrm{Re}$ is dimensionless and hence, write the final form of the differential equation using the Reynolds number.

:::{.callout-note collapse="true"}
# Non-dimensionality of the Reynolds Number

$$[\mathrm{Re}]=\frac{[x] [u]}{[\nu]}=\left( \mathrm{m} \right) \, \left( \mathrm{m} \, \mathrm{s}^{-1} \right) \, \left(\mathrm{m}^{-2} \, \mathrm{s}^{-1} \right)^{-1}=1$$

Therefore, this gives the non-dimensional Navier-Stokes equation for fluid flow
$$\frac{\partial \boldsymbol{u}}{\partial t}+\left( \boldsymbol{u} \cdot \nabla \right)\boldsymbol{u}=-\nabla p+\frac{1}{\mathrm{Re}} \nabla^2 \boldsymbol{u}.$$
:::

5.  Give an interpretation of the Reynolds number and what happens as $\mathrm{Re} \to \infty$ and $\mathrm{Re} \to 0$.


:::{.callout-note collapse="true"}
# The Reynolds Number

The Reynolds number $\mathrm{Re}$ gives a measure for the effect of viscosity for fluid flow or for the movement through a fluid.  As $\mathrm{Re}$ gets larger, the fluid becomes less viscous hence reducing the effect of viscosity on the movement and the inertial forces dominate. (The case when $\mathrm{Re} \to \infty$ is called inviscid flow where there is no viscosity.)  As $\mathrm{Re}$ decreases, the viscosity increases, making the movement depend on the viscous forces more than the inertial forces.

The Reynolds number is important in modelling since when length and speed scales change from full-sized objects to smaller models (like models of cars and buildings for testing purposes), the same environment cannot be translated from one to the other (since a full sized building in 20mph winds will not move whereas 20mph winds on a small scale of model of the building will be affected much more).  However, if the Reynolds number is fixed in both cases, the model can be made more realistic.
:::
